### ISSUE TITLE
Map failed to load in Everest

### ISSUE THREAD

**Issue by AshotlWotl** [CelestialCartographers/Loenn#57]
I was making my map, went to test it and this happened.

(10/18/2023 12:51:24) [Everest] [Info] [debugrc] Started DebugRC thread, available via http://localhost:32270/
(10/18/2023 12:51:45) [Everest] [Info] [LevelLoader] Loading Ashotl Wotl/Transcendence/1-Hit Space to Start
(10/18/2023 12:51:45) [Everest] [Warn] [LevelLoader] Failed loading Ashotl Wotl/Transcendence/1-Hit Space to Start
--------------------------------
Detailed exception log:
--------------------------------
System.ArgumentException: Requested value 'Up' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Enum.Parse(Type enumType, String value)
   at Celeste.MapData.ParseBackdrop(Element child, Element above)
   at Celeste.MapData.CreateBackdrops(Element data)
   at Celeste.LevelLoader.LoadingThread()
   at Celeste.LevelLoader.LoadingThread_Safe() in /home/vsts/work/1/s/Celeste.Mod.mm/Patches/LevelLoader.cs:line 203

How do i fix this. Also when can i do my background.

**Comment by AshotlWotl** [comment]
this was solved on discord
*in the code the tentacles background doesnt have a value of up but top*
